export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT'
export const NEW_NAME = 'NEW_NAME'
export const NEW_PRICE = 'NEW_PRICE'
export const NEW_IMAGE = 'NEW_IMAGE'
export const NEW_DESC = 'NEW_DESC'
